version: '3.9'

services:
  web:
    # Execute the main.py script
    command: python3 server.py
    # Use the specified image from Docker Hub
    image: lemj/st124895:v1
    # For MAC M1 users
    platform: linux/x86_64
    # Set environment variables so the app runs on 0.0.0.0:80
    environment:
      - HOST=0.0.0.0
      - PORT=80
    # Traefik labels for reverse proxy configuration
    labels:
      - traefik.enable=true
      - traefik.http.services.web-st124895.loadbalancer.server.port=80
      # Uncomment and modify the following line if you wish to change the subdomain
      - traefik.http.routers.web-st124895.rule=Host(`st124895.ml.brain.cs.ait.ac.th`)
      - traefik.http.routers.web-st124895.tls=true
      - traefik.http.routers.web-st124895.tls.certresolver=production
      - traefik.http.routers.web-st124895.entrypoints=websecure
    networks:
      - default
      - traefik_default

networks:
  default:
  traefik_default:
    external: true
